### ISSUE TITLE
[=BUG=] Sign in to confirm your age

### ISSUE THREAD

**Issue by aiko-chan-ai** [play-dl/play-dl#241]
#### Describe the bug

i got this error when using playdl.video_info()
```js
Error: While getting info from url
Sign in to confirm your age
     at video_basic_info (C:\Users\Aiko\Desktop\Sagiri-v3\3.3\node_modules\play-dl\dist\index.js:1:16659)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async Object.video_info (C:\Users\Aiko\Desktop\Sagiri-v3\3.3\node_modules\play-dl\dist\index.js:3:943)
```
I have set a cookie for the module, because when I use ytdl-core with the same cookie I don't get this error
What is the solution for me?

 - Node.js version: 16.13.0
 - OS & version: Windows 10 Education x64 Build 19043.928

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest LTS version of Node.js and Play-dl.

**Comment by killer069** [comment]
Maybe your cookies are expired.

Try to follow [instructions](https://github.com/play-dl/play-dl/tree/main/instructions#youtube-cookies) and get fresh cookies.
