### ISSUE TITLE
[=BUG=] Initial Player Response undefined

### ISSUE THREAD

**Issue by killer069** [play-dl/play-dl#252]
this happends to me today, and I saw a lot of this error happened when I try to use `video_basic_info` function.
even if I tried to use `htmldata`, it still happen.

`play-dl@1.8.6`

![image](https://user-images.githubusercontent.com/33802653/153122186-58dbbb1d-cca5-4873-9368-8312dada3922.png)

_Originally posted by @Gary50613 in https://github.com/play-dl/play-dl/issues/147#issuecomment-1033337425_

**Comment by killer069** [comment]
@Gary50613

I need to ask few questions.

- Bot hosting location & it is inside europe or outside europe.
- YouTube url which created this issue.

**Comment by Mistelteyn** [comment]
@killer069 

Same thing happened to me today, If I kept retrying like 3-5 times it would work eventually.

Bot hosting location & it is inside europe or outside europe.
- Heroku (United States)
- Also tested locally and still happens (PH)

YouTube url which created this issue.
- Almost all video I tried to play but here are some links
- -https://www.youtube.com/watch?v=g92IwF_8tks
- -https://www.youtube.com/watch?v=9BMwcO6_hyA
- -https://www.youtube.com/watch?v=NrgmdOz227I
- - https://www.youtube.com/watch?v=PjJBLHBWf5I


Error happened here 
![image](https://user-images.githubusercontent.com/37813964/153143892-99a889fa-446d-477f-9119-a0d072bb419d.png)

Error in Console log
![image](https://user-images.githubusercontent.com/37813964/153144162-ef097dd2-5957-4e68-ba6b-94ac488af417.png)

**Comment by Gary50613** [comment]
> @killer069
> 
> Same thing happened to me today, If I kept retrying like 3-5 times it would work eventually.
> 
> Bot hosting location & it is inside europe or outside europe.
> 
> * Heroku (United States)
> * Also tested locally and still happens (PH)
> 
> YouTube url which created this issue.
> 
> * Almost all video I tried to play but here are some links
> * -https://www.youtube.com/watch?v=g92IwF_8tks
> * -https://www.youtube.com/watch?v=9BMwcO6_hyA
> * -https://www.youtube.com/watch?v=NrgmdOz227I
> * * https://www.youtube.com/watch?v=PjJBLHBWf5I
> 
> Error happened here ![image](https://user-images.githubusercontent.com/37813964/153143892-99a889fa-446d-477f-9119-a0d072bb419d.png)
> 
> Error in Console log ![image](https://user-images.githubusercontent.com/37813964/153144162-ef097dd2-5957-4e68-ba6b-94ac488af417.png)

same hosting on `heroku US` and when i tried to test on my local pc (Taiwan) it also shows this error sometimes with same url

- url I'm using https://www.youtube.com/watch?v=qDL3zhB8-MM

**Comment by iSwanGit** [comment]
It happened to me (recognized since Feb 8 23:55 UTC)

I updated play-dl (to `1.8.6`) too, but still happen.

### Answers about questions
- Hosting location: Asia (South Korea), docker on on-premise server
- YouTube url:
  - https://www.youtube.com/watch?v=Rh9nhTjjKTc
  - https://www.youtube.com/watch?v=_vp7TLLse3A
  - https://www.youtube.com/watch?v=jdQWia3fwMU
  - https://www.youtube.com/watch?v=c24qa1ucBkI
  - and many other...
- ERROR OCCURS RANDOMLY, There are several times when errors don't occur to same url.

### Error occurs here
![image](https://user-images.githubusercontent.com/10243897/153145712-4168f99f-5d83-4078-af4c-db76002f2a11.png)


### Logs
timezone is Asia/Seoul (UTC+9).
```log
[2022/02/09 10:16:17.659] DB pool created
[2022/02/09 10:16:17.685] 0 configs overrided
[2022/02/09 10:16:17.686] All configs are loaded
[2022/02/09 10:16:18.949] Start refreshing application (/) commands...
[2022/02/09 10:16:18.950] Refreshing server(guild) info...
[2022/02/09 10:16:18.950] Ready!
[2022/02/09 10:16:19.208] DiscordAPIError: Missing Access (822303774244601911, tmi holdings)
[2022/02/09 10:16:19.457] refresh end
[2022/02/09 10:19:06.128] [MikuMikuKorea] 검색 중: https://music.youtube.com/watch?v=c24qa1ucBkI&t=300
[2022/02/09 10:19:06.431] [33mWARNING:[0m ytdl-core is out of date! Update with "npm install ytdl-core@latest".
[2022/02/09 10:19:07.109] 검색된 YouTube 영상: Stellar Magic Night (39 mix) (feat. Hatsune Miku) (c24qa1ucBkI) (306초)
[2022/02/09 10:19:07.109] [MikuMikuKorea] 음성 채널 연결 중...
[2022/02/09 10:19:07.110] [MikuMikuKorea] 대기열 전송 중...
[2022/02/09 10:19:07.311] [MikuMikuKorea] DJ Yurika V2 joined bot test
[2022/02/09 10:19:07.502] Error: Initial Player Response Data is undefined.
    at video_stream_info (/home/djyurika/djyurika_js/node_modules/play-dl/dist/index.js:2:3266)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async stream (/home/djyurika/djyurika_js/node_modules/play-dl/dist/index.js:7:15816)
    at async Object.stream (/home/djyurika/djyurika_js/node_modules/play-dl/dist/index.js:15:3146)
[2022/02/09 10:19:07.502] Song url was https://www.youtube.com/watch?v=c24qa1ucBkI
[2022/02/09 10:19:07.998] [MikuMikuKorea] 랜덤 선곡: Nightscape/R Sound Design feat. 初音ミク (iiJJ3LJEje8)
[2022/02/09 10:19:08.271] [MikuMikuKorea] 연결 됨: bot test (by EleMas*)
[2022/02/09 10:19:08.580] [MikuMikuKorea] 재생: Nightscape/R Sound Design feat. 初音ミク
[2022/02/09 10:19:08.584] Update permalink to DB column
/home/djyurika/djyurika_js/node_modules/play-dl/dist/index.js:2
${o.playabilityStatus.errorScreen.playerErrorMessageRenderer?.reason.simpleText??o.playabilityStatus.errorScreen.playerKavRenderer?.reason.simpleText}`);let f=l.contents.twoColumnWatchNextResults.results?.results?.contents[1]?.videoSecondaryInfoRenderer?.owner?.videoOwnerRenderer,y=f?.badges?.[0]?.metadataBadgeRenderer?.style?.toLowerCase(),b=`https://www.youtube.com${i.split('"jsUrl":"')[1].split('"')[0]}`,D=[];l.contents.twoColumnWatchNextResults.secondaryResults.secondaryResults.results.forEach(m=>{m.compactVideoRenderer&&D.push(`https://www.youtube.com/watch?v=${m.compactVideoRenderer.videoId}`),m.itemSectionRenderer?.contents&&m.itemSectionRenderer.contents.forEach(C=>{C.compactVideoRenderer&&D.push(`https://www.youtube.com/watch?v=${C.compactVideoRenderer.videoId}`)})});let z=o.microformat.playerMicroformatRenderer,ke=l.contents.twoColumnWatchNextResults.results.results.contents?.[1]?.videoSecondaryInfoRenderer?.metadataRowContainer?.metadataRowContainerRenderer?.rows,W=[];ke&&ke.forEach(m=>{if(!m.metadataRowRenderer)return;let C=m.metadataRowRenderer.title.simpleText??m.metadataRowRenderer.title.runs[0].text;if(C.toLowerCase()==="song")W.push({}),W[W.length-1].song=m.metadataRowRenderer.contents[0].simpleText??m.metadataRowRenderer.contents[0]?.runs?.[0]?.text;else{if(W.length===0)return;W[W.length-1][C.toLowerCase()]=m.metadataRowRenderer.contents[0].simpleText??m.metadataRowRenderer.contents[0]?.runs?.[0]?.text}});let Le=new S({id:c.videoId,title:c.title,description:c.shortDescription,duration:Number(c.lengthSeconds),duration_raw:ti(c.lengthSeconds),uploadedAt:z.publishDate,thumbnails:c.thumbnail.thumbnails,channel:{name:c.author,id:c.channelId,url:`https://www.youtube.com/channel/${c.channelId}`,verified:Boolean(y?.includes("verified")),artist:Boolean(y?.includes("artist")),icons:f?.thumbnail?.thumbnails||void 0},views:c.viewCount,tags:c.keywords,likes:parseInt(l.contents.twoColumnWatchNextResults.results.results.contents.find(m=>m.videoPrimaryInfoRenderer)?.videoPrimaryInfoRenderer.videoActions.menuRenderer.topLevelButtons?.find(m=>m.toggleButtonRenderer.defaultIcon.iconType==="LIKE")?.toggleButtonRenderer.defaultText.accessibility?.accessibilityData.label.replace(/\D+/g,"")??0),live:c.isLiveContent,private:c.isPrivate,discretionAdvised:u,music:W}),qe=o.streamingData.formats??[];return qe.push(...o.streamingData.adaptiveFormats??[]),{LiveStreamData:{isLive:Le.live,dashManifestUrl:o.streamingData?.dashManifestUrl??null,hlsManifestUrl:o.streamingData?.hlsManifestUrl??null},html5player:b,format:qe,video_details:Le,related_videos:D}}a(X,"video_basic_info");async function V(t,e={}){if(typeof t!="string")throw new Error("url parameter is not a URL string or a string of HTML");let i,r={};if(e.htmldata)i=t;else{let y=De(t);if(!y)throw new Error("This is not a YouTube Watch URL");let b=`https://www.youtube.com/watch?v=${y}&has_verified=1`;i=await h(b,{headers:{"accept-language":"en-US,en;q=0.9"},cookies:!0,cookieJar:r})}if(i.indexOf("Our systems have detected unusual traffic from your computer network.")!==-1)throw new Error("Captcha page: YouTube has detected that you are a bot!");let s=i.split("var ytInitialPlayerResponse = ")?.[1]?.split(";<\/script>")[0].split(/;\s*(var|const|let)\s/)[0];if(!s)throw new Error("Initial Player Response Data is undefined.");let n=JSON.parse(s);if(n.playabilityStatus.status!=="OK")if(n.playabilityStatus.status==="CONTENT_CHECK_REQUIRED"){if(e.htmldata)throw new Error(`Accepting the viewer discretion is not supported when using htmldata, video: ${n.videoDetails.videoId}`);let y=i.split("var ytInitialData = ")?.[1]?.split(";<\/script>")[0].split(/;\s*(var|const|let)\s/)[0];if(!y)throw new Error("Initial Response Data is undefined.");let b=JSON.parse(y).topbar.desktopTopbarRenderer.interstitial?.consentBumpV2Renderer.agreeButton.buttonRenderer.command.saveConsentAction;b&&Object.assign(r,{VISITOR_INFO1_LIVE:b.visitorCookie,CONSENT:b.consentCookie});let D=await it(n.videoDetails.videoId,r,i,!1);n.streamingData=D.streamingData}else throw new Error(`While getting info from url
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

Error: Initial Player Response Data is undefined.
    at video_stream_info (/home/djyurika/djyurika_js/node_modules/play-dl/dist/index.js:2:3266)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ue.retry (/home/djyurika/djyurika_js/node_modules/play-dl/dist/index.js:7:6838)
    at async ue.loop (/home/djyurika/djyurika_js/node_modules/play-dl/dist/index.js:7:7364)
```

**Comment by iSwanGit** [comment]
OMG YouTube detected play-dl is a bot

![image](https://user-images.githubusercontent.com/10243897/153146094-d40a284d-f7b5-41c9-9cdf-992aa607ceff.png)

**Comment by Gary50613** [comment]
> OMG YouTube detected play-dl is a bot
> 
> ![image](https://user-images.githubusercontent.com/10243897/153146094-d40a284d-f7b5-41c9-9cdf-992aa607ceff.png)

maybe try to refresh cookie or change IP can fix this

**Comment by Gary50613** [comment]
![image](https://user-images.githubusercontent.com/33802653/153151828-bf5f0d7c-d582-4ff1-a215-4b76cfcccf80.png)

hmm no initial data? is youtube working on some update?

**Comment by iSwanGit** [comment]
> OMG YouTube detected play-dl is a bot

@Gary50613 I'm sorry, I saw just a part of script definition in error response body so that I got confused

**Comment by killer069** [comment]
> hmm no initial data? is youtube working on some update?

Yup youtube removed Internet Explorer 11 support.

**Comment by killer069** [comment]
Hope your issues are fixed in latest release.
