### ISSUE TITLE
[=BUG=] Getting info for a youtube "mix" playlist throws an error

### ISSUE THREAD

**Issue by i1u5** [play-dl/play-dl#322]
#### Describe the bug

 - Node.js version: 16.17.1 LTS
 - OS & version: Ubuntu 20.04.5 LTS

The issue doesn't seem to happen for me while testing in Windows, but does on my server so maybe it is something related to a UI change?

#### Actual behavior

```
TypeError: Cannot read properties of undefined (reading 'playlist')

 at getWatchPlaylist (/workspace/node_modules/play-dl/play-dl/YouTube/utils/extractor.ts:711:83)

 at Object.playlist_info (/workspace/node_modules/play-dl/play-dl/YouTube/utils/extractor.ts:545:16)

 at processTicksAndRejections (node:internal/process/task_queues:96:5)

 at Object.execute (/workspace/src/commands/music/play.ts:85:24)

 at Client.<anonymous> (/workspace/src/index.ts:59:4)
```

#### Code to reproduce

```js
const url = "https://www.youtube.com/watch?v=RYr96YYEaZY&list=RDRYr96YYEaZY";
const playlist = await play.playlist_info(url, { incomplete: true });
console.log(playlist.title);

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by BTX-ON-YT** [comment]
YouTube mixes are personalized to your account and i believe are private you could try the youtube auth process [](https://github.com/play-dl/play-dl/tree/9661d8f17acc0381a14ce315867235719d28fc24/instructions)

**Comment by BTX-ON-YT** [comment]
It looks like Youtube cookies are not passed to playlist calls ill reply when i have a solution

**Comment by EasyXploit** [comment]
Any news on this?  @AtariTom
