### ISSUE TITLE
[=BUG=] search function returned undefined

### ISSUE THREAD

**Issue by muhahahahe** [play-dl/play-dl#360]
#### Describe the bug

 - Node.js version: 18.15.0
 - OS & version: Ubuntu 22.04

While searching for a youtube video the search function returned an undefined at index 0

#### Actual behavior

returning undefined

#### Expected behavior

returning YouTubeVideo

#### Code to reproduce

```ts
let result: YouTubeVideo | null = null;
try {
	result = (
		await search(query, {
			limit: 1,
			source: {
				youtube: 'video',
			},
		})
	)[0];
} catch (error) {
	return 'No results found.';
}
```

#### ConsoleLog
```
node:events:491
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read properties of undefined (reading 'title')
    at searchYoutube (/usr/src/bot/utils/utils.js:313:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (/usr/src/bot/classes/Main.js:70:35)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by muhahahahe** [comment]
i just encountered it once so far and i check now if the result is there to prevent that but according to the search function return it should give me a YouTubeVideo[] and never an undefined

**Comment by MerfAvenger** [comment]
Can you add more context i.e. the function that executes the code you've defined above and what term you were searching for. 

~~From the error, it sounds like you are getting 0 results for the video and processing that later on - result will be an _empty_ array if there are no results for the video, so trying to read the title in your `searchYoutube` function mentioned in the stack trace will fail. The search function does not throw an error if there are no results, so your `try/catch` will only help you if the request is rejected with an error, something that might happen if there is a 429 rate limiting error or authentication/age verification error.~~ Noticed the `[0]` and that definitely makes this more interesting. Can you add the search term and I'll check out that video too?

Have you tried searching for the exact term on YouTube itself and seeing if there are any results?

**Comment by muhahahahe** [comment]
the problem is that bot runs in multiple servers i would have to find out who made the search and then they need to remember what they searched for :D
you can look at it here : https://github.com/muhahahahe/pomn_music/blob/main/src/utils/utils.ts
line 304

but all in all if this was an age restricted or other video that couldnt be found, it would be nice to get that from the function before i want to process it
because the function says it returns an array of YouTubeVideo, which it obviously didnt

**Comment by muhahahahe** [comment]
i added this so if it happens again i can give you the search string
```
	if (!result) {
		console.log(`Search that returned undefined: ${query}`);
		return 'No results found.';
	}
```

**Comment by muhahahahe** [comment]
so i got one for you, and it turns out its due to someone not able to read the help of the bot, also i got another error i cant explain how that happened:

```
Search that returned undefined: play https://www.youtube.com/watch?v=5C5ULnY_PXs&t=4s&ab_channel=LoganWeber
Search that returned undefined: play https://www.youtube.com/watch?v=sei7fmpXL_I&t=54s&ab_channel=CarlosCardenasMedina
```

they were typing play before the link, anyways that should still never return an undefined 

the other error for which i probably should open another issue:

```
TypeError: Cannot read properties of undefined (reading 'split')
    at extractVideoId (/usr/src/bot/node_modules/play-dl/dist/index.js:1:15479)
    at video_basic_info (/usr/src/bot/node_modules/play-dl/dist/index.js:1:16113)
    at getYoutube (/usr/src/bot/utils/utils.js:337:55)
    at Client.<anonymous> (/usr/src/bot/classes/Main.js:96:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
