### ISSUE TITLE
[=BUG=] play.validate() throws an error with Soundcloud link

### ISSUE THREAD

**Issue by LiWinDom** [play-dl/play-dl#373]
#### Describe the bug

 - Node.js version: `20.15.0`
 - OS & version: tested on `Ubuntu 22.04.4 LTS` and `MacOS 15.0 Beta 4`

`play.validate()` throws an error with Soundcloud link

#### Actual behavior

```
Uncaught TypeError: Cannot read properties of undefined (reading 'client_id')
    at so_validate (/Users/LiWinDom/Documents/Code/_bots/LWDbot-discord/node_modules/play-dl/dist/index.js:14:2106)
    at Object.validate (/Users/LiWinDom/Documents/Code/_bots/LWDbot-discord/node_modules/play-dl/dist/index.js:15:4060)
    at REPL2:1:50
```

#### Expected behavior

Return value of `so_playlist` or `so_track`

#### Code to reproduce

```js
const play = require('play-dl');
const type = await play.validate("https://soundcloud.com/leechplus/scripting?in=leechplus/sets/the-osaka-operating-system-vol");
```

#### ScreenShots
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/287670a0-c825-459e-87e6-c9c207ba062b">

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by aquie00tt** [comment]
## Solution

The issue is not due to a bug in the `validate` function but rather because `setToken({ soundcloud: { client_id: "123" } })` is not properly defined.

### Solution Recommendation

You should provide the `setToken` function with a correctly configured token object. For example, include the `client_id` parameter required for SoundCloud:
```ts
setToken({ soundcloud: { client_id: "123" } });
