### ISSUE TITLE
[=BUG=] Can't play any music

### ISSUE THREAD

**Issue by OmegaM1** [play-dl/play-dl#381]
#### Describe the bug

 - Node.js version: ^20.9.0
 - OS & version: Host (linux)

#### Actual behaviorError: Got 429 from the request
    at /home/container/node_modules/play-dl/dist/index.js:1:4158
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

#### Error:

```js
Error: Got 429 from the request
    at /home/container/node_modules/play-dl/dist/index.js:1:4158
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by Odogo** [comment]
A 429 error code means you're sending too many requests to the API, and it doesn't like it. You're being rate-limited, basically.

If you can send a code snippet of roughly where this error is occurring (such as the executed command, or similar), others more knowledgeable could help you, or I could give a whack at it as well.

But, from what I've tinkered with, you're making too many fetch and/or stream requests. I found this extremely common with Spotify when submitting a playlist or album with over 100 songs (using my code, which could be vastly different to what you're doing). YouTube or Soundcloud I don't know if they have this limitation, but I've not had any trouble with YouTube in doing something similar.

**Comment by OmegaM1** [comment]
> A 429 error code means you're sending too many requests to the API, and it doesn't like it. You're being rate-limited, basically.

I'm trying to use youtube to play musics, and no I never sent many requests to the API, my bot is running on an online host with a static ip which you can't change the host ip because of lacking permissions so that static ip is probably the reason causing the error, but I got no idea how to fix it since you can't do anything other than starting and restarting the host

This is a part of my code that plays music from youtube

```js
let yt_info = await play.search(args, {
          limit: 1
        })

let stream = await play.stream(yt_info[0].url, { filter: "audio" })

        let resource = createAudioResource(stream.stream, {
          inputType: stream.type
        })

        let player = createAudioPlayer({
          behaviors: {
            noSubscriber: NoSubscriberBehavior.Play
          }
        })
        player.play(resource)
        connection.subscribe(player)
```
