### ISSUE TITLE
[=BUG=] Sign in to confirm your age

### ISSUE THREAD

**Issue by exewax** [play-dl/play-dl#82]
- Node.js version: V16.9.1 
 - OS & version: Linux/Debian 10

When we request a youtube URL with `stream(url)` if the video is subject to an age limit the bot crash with this error

```
/home/debian/discord_music/node_modules/play-dl/dist/YouTube/utils/extractor.js:67
throw new Error(`While getting info from url\n${(_k = (_j = player_response.playabilityStatus.errorScreen.playerErrorMessageRenderer) === null || _j === void 0 ? void 0 : _j.reason.simpleText) !== null && _k !== void 0 ? _k : (_l = player_response.playabilityStatus.errorScreen.playerKavRenderer) === null || _l === void 0 ? void 0 : _l.reason.simpleText}`);

Error: While getting info from url
Sign in to confirm your age
    at video_basic_info (/home/debian/discord_music/node_modules/play-dl/dist/YouTube/utils/extractor.js:67:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.video_info (/home/debian/discord_music/node_modules/play-dl/dist/YouTube/utils/extractor.js:120:16)
    at async Object.stream (/home/debian/discord_music/node_modules/play-dl/dist/YouTube/stream.js:27:16)
    at async module.exports (/home/debian/discord_music/module/playRandomMusic.js:22:18)
    at async AudioPlayer.<anonymous> (/home/debian/discord_music/module/clentReady.js:22:20)
```

**Comment by killer069** [comment]
Either provide [cookies](https://github.com/play-dl/play-dl/tree/main/docs/YouTube#stream) or catch the error from the stream promise.
