### ISSUE TITLE
[=BUG=] .toJSON

### ISSUE THREAD

**Issue by joelmagner** [play-dl/play-dl#84]
#### Describe the bug

 - Node.js version: 16.9.1
 - OS & version: Mac OS Big Sur

#### Code to reproduce

```js
    import * as play from "play-dl";
    ...
    let yt_info = await play.search("nestor 1989 audio", { limit: 1 });
    console.log(yt_info[0].toJSON);
```

#### Error
```
/Users/X/Documents/git/X/node_modules/play-dl/dist/YouTube/classes/Video.js:41
            thumbnail: (_a = this.thumbnail) === null || _a === void 0 ? void 0 : _a.toJSON(),
                                                                                     ^

TypeError: _a.toJSON is not a function
    at Video.get toJSON [as toJSON] (/Users/X/Documents/git/X/node_modules/play-dl/dist/YouTube/classes/Video.js:41:86)
    at App.<anonymous> (/Users/jX/Documents/git/X/dist/app.js:73:48)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/X/Documents/git/X/dist/app.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
Oh I see, I will fix it.
